trigger:
  branches:
    include:
      - tests_enhacements

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    sudo apt-get update
    sudo apt-get install -y google-chrome-stable
  displayName: 'Install Google Chrome'

# Install frontend dependencies, build, and serve in production mode
- script: |
    npm install
    npm run build
    npm install -g serve
    serve -s build &
  displayName: 'Build and Serve Frontend'

# Install backend dependencies and start backend
- script: |
    cd ./app-management
    npm install
    npm start &
  displayName: 'Start Backend'

# Wait for both frontend and backend to start
- script: |
    sleep 10
  displayName: 'Wait for Servers to Start'

# Check if frontend is accessible
- script: |
    curl http://localhost:3000
  displayName: 'Check Frontend Availability'

# Ensure junit-results directory exists
- script: |
    mkdir -p ./webdriverio_test_project/junit-results
  displayName: 'Ensure junit-results Directory Exists'

# Run WebdriverIO tests with debug logs
- script: |
    echo "Running WebdriverIO tests..."
    cd ./webdriverio_test_project
    npm install
    npm install chromedriver --latest
    npx cross-env DEBUG=1 USE_LOCAL=1 wdio run wdio.conf.js --suite e2e
  displayName: 'Run WebdriverIO Tests'

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: './webdriverio_test_project/junit-results/*.xml'
    failTaskOnFailedTests: false
