trigger:
  branches:
    include:
      - tests_enhacements  #branch

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x' 
  displayName: 'Install Node.js'

# Step to install frontend dependencies and build the frontend
- script: |
    npm install
    npm run build  
  displayName: 'Build Frontend'

# Step to install backend dependencies and run the backend
- script: |
    cd ./app-management 
    npm install
    npm start  
  displayName: 'Start Backend'

# Step to run WebdriverIO tests
- script: |
    cd ./webdriverio_test_project
    ls
    npm install  
    npx wdio
    ls
  displayName: 'Run WebdriverIO Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'
    failTaskOnFailedTests: true
