trigger:
  branches:
    include:
      - tests_enhacements

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Install frontend dependencies and start the frontend in development mode
- script: |
    npm install
    npm start &
  displayName: 'Start Frontend'

# Install backend dependencies and start the backend in development mode
- script: |
    cd ./app-management
    npm install
    npm start &
  displayName: 'Start Backend'

# Wait for both frontend and backend to start (optional, can adjust timeout)
- script: |
    sleep 10
  displayName: 'Wait for Servers to Start'

# Run WebdriverIO tests after both servers are up
- script: |
    echo "Running WebdriverIO tests..."
    cd ./webdriverio_test_project
    npm install
    npm run test:local
    exitCode=$?
    echo "Test exit code: $exitCode"
    if [ $exitCode -ne 0 ]; then
      echo "Tests failed."
      exit 1
    fi
  displayName: 'Run WebdriverIO Tests'

# Check for junit-results directory
- script: |
    cd ./webdriverio_test_project
    ls -al junit-results
  displayName: 'Check Test Results Directory'

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: './webdriverio_test_project/junit-results/*.xml'
    failTaskOnFailedTests: true
