trigger:
  branches:
    include:
      - tests_enhacements  # Your branch

pool:
  vmImage: 'windows-latest'  # Windows has pre-configured Chrome and ChromeDriver

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x' 
  displayName: 'Install Node.js'

# Step to install frontend dependencies and build the frontend
- script: |
    npm install
    npm run build  
  displayName: 'Build Frontend'

# Step to install backend dependencies and run the backend
- script: |
    cd ./app-management 
    npm install
    npm start  
  displayName: 'Start Backend'

# Step to install WebdriverIO dependencies and run tests
- script: |
    cd ./webdriverio_test_project
    npm install
    npm run test:local
  displayName: 'Run WebdriverIO Tests'

# Step to list contents of junit-results directory
- script: |
    cd ./webdriverio_test_project
    ls -al junit-results
  displayName: 'Verify Test Results Directory'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'
    failTaskOnFailedTests: true
