trigger:
  branches:
    include:
      - tests_enhacements

pool:
  vmImage: 'ubuntu-latest'

variables:
  TEST_USERNAME: 'kasiakasia' # Replace with your test username
  TEST_PASSWORD: 'kasiakasia' # Replace with your test password
  CI: 'true' # Indicate that this is a CI environment

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Install Google Chrome
- script: |
    sudo apt-get update
    sudo apt-get install -y google-chrome-stable
  displayName: 'Install Google Chrome'

# Install frontend dependencies, build, and serve in production mode
- script: |
    npm install
    npm run build
    npm install -g serve
    serve -s build &
  displayName: 'Build and Serve Frontend'

# Install backend dependencies and start backend
- script: |
    cd ./app-management
    npm install
    export NODE_ENV=local
    npm start &
  displayName: 'Start Backend'

# Wait for backend to start
- script: |
    echo "Waiting for backend to start..."
    for i in {1..30}; do
      curl --silent http://localhost:5000 && break
      echo "Backend not ready yet, retrying..."
      sleep 2
    done
  displayName: 'Wait for Backend to Start'

# Ensure junit-results directory exists
- script: |
    mkdir -p ./webdriverio_test_project/junit-results
  displayName: 'Ensure junit-results Directory Exists'

- script: |
    echo "Listing test results directory:"
    ls -la ./webdriverio_test_project/junit-results
  displayName: "Debug Test Results Directory"


# check if dir exists 
- script: |
    echo "Checking file paths:"
    find ./webdriverio_test_project/test/pages -name "navTabs.js"
  displayName: "Debug File Paths"

- script: |
    echo "Testing file paths:"
    ls -la ./webdriverio_test_project/test/pages/
    ls -la ./webdriverio_test_project/test/utilities/
    ls -la ./webdriverio_test_project/test/specs/
  displayName: "Check File Paths"

- script: |
    echo "Listing all spec files:"
    find ./webdriverio_test_project/test/specs/
  displayName: "List Spec Files"

- script: |
    mkdir -p ./webdriverio_test_project/error_screenshots
  displayName: "Create Error Screenshots Directory"


# Run WebdriverIO tests with debug logs
- script: |
    echo "Running WebdriverIO tests..."
    cd ./webdriverio_test_project
    npm install
    npm install chromedriver --latest
    ls
    npx cross-env DEBUG=1 USE_LOCAL=1 TEST_USERNAME=$(TEST_USERNAME) TEST_PASSWORD=$(TEST_PASSWORD) wdio run wdio.conf.js --suite e2e
  displayName: 'Run WebdriverIO Tests'

- script: |
    echo "Listing test results directory:"
    ls -la ./webdriverio_test_project/junit-results
  displayName: "Debug Test Results Directory"

- script: |
    echo "Testing file paths:"
    ls -la ./webdriverio_test_project/
  displayName: "Check File Paths"

- script: |
    sleep 5
  displayName: "Wait Before Publishing Results"

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: './webdriverio_test_project/junit-results/*.xml'
    condition: always()
