trigger:
  branches:
    include:
      - tests_enhacements

pool:
  vmImage: 'ubuntu-latest'  # Switching to a Linux-based agent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x' 
  displayName: 'Install Node.js'

# Install frontend dependencies and build the frontend
- script: |
    npm install
    npm run build  
  displayName: 'Build Frontend'

# Install backend dependencies and start the backend
- script: |
    cd ./app-management 
    npm install
    npm start &
  displayName: 'Start Backend'

# Run WebdriverIO tests
- script: |
    echo "Running WebdriverIO tests..."
    cd ./webdriverio_test_project
    npm install
    npm run test:local
    exitCode=$?
    echo "Test exit code: $exitCode"
    if [ $exitCode -ne 0 ]; then
      echo "Tests failed."
      exit 1
    fi
  displayName: 'Run WebdriverIO Tests'

# Check for junit-results directory
- script: |
    cd ./webdriverio_test_project
    ls -al junit-results
  displayName: 'Check Test Results Directory'

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'
    failTaskOnFailedTests: true
