trigger:
  branches:
    include:
      - tests_enhacements  # Your branch

pool:
  vmImage: 'windows-latest'  # Windows has pre-configured Chrome and ChromeDriver

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x' 
  displayName: 'Install Node.js'

# Step to install frontend dependencies and build the frontend
- script: |
    npm install
    npm run build  
  displayName: 'Build Frontend'

# Step to install backend dependencies and run the backend
- script: |
    cd ./app-management 
    npm install
    npm start  
  displayName: 'Start Backend'

# Step to check if Chrome is running
- script: |
    tasklist /fi "imagename eq chrome.exe"
  displayName: 'Check Chrome Process'

# Ensure junit-results Directory Exists (Windows compatible)
- script: |
    if not exist .\webdriverio_test_project\junit-results mkdir .\webdriverio_test_project\junit-results
  displayName: 'Ensure junit-results Directory Exists'

# Print Working Directory (before tests)
- script: |
    pwd
  displayName: 'Print Working Directory1'

- script: |
    echo "Running WebdriverIO tests..."
    cd ./webdriverio_test_project
    npm install
    npm run test:local
    echo "WebdriverIO tests completed."
  displayName: 'Run WebdriverIO Tests'

# Print Working Directory (after tests)
- script: |
    pwd
  displayName: 'Print Working Directory2'

# Verify junit-results Directory Contents
- script: |
    cd ./webdriverio_test_project
    ls -al junit-results
  displayName: 'Verify Test Results Directory'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'
    failTaskOnFailedTests: true
