trigger:
  branches:
    include:
      - tests_enhacements

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Install frontend dependencies, build, and serve in production mode
- script: |
    npm install
    npm run build
    npm install -g serve
    serve -s build &
  displayName: 'Build and Serve Frontend'

# Install backend dependencies and start backend
- script: |
    cd ./app-management
    npm install
    npm start &
  displayName: 'Start Backend'

# Wait for both frontend and backend to start
- script: |
    sleep 10
  displayName: 'Wait for Servers to Start'

# Check if frontend is accessible
- script: |
    curl http://localhost:3000
  displayName: 'Check Frontend Availability'

# Ensure junit-results directory exists
- script: |
    mkdir -p ./webdriverio_test_project/junit-results
  displayName: 'Ensure junit-results Directory Exists'

# Run WebdriverIO tests with debug logs
- script: |
    echo "Running WebdriverIO tests..."
    cd ./webdriverio_test_project
    npm install
    npx wdio run wdio.conf.js --logLevel debug
    exitCode=$?
    echo "Test exit code: $exitCode"
    if [ $exitCode -ne 0 ]; then
      echo "Tests failed."
      exit 1
    fi
    ls
  displayName: 'Run WebdriverIO Tests'

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: './webdriverio_test_project/junit-results/*.xml'
    failTaskOnFailedTests: true
