trigger:
  branches:
    include:
      - tests_enhacements  # branch here

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'  # Node.js version
  displayName: 'Install Node.js'

# Step to install frontend dependencies and build the frontend
- script: |
    npm install
    npm run build  # This builds the frontend
  displayName: 'Build Frontend'

# Step to install backend dependencies and run the backend
- script: |
    cd ./app-management  # Change to your backend directory
    npm install
    npm start  # Starts the backend server
  displayName: 'Start Backend'

# Step to run WebdriverIO tests
- script: |
    cd ./webdriverio_test_project  # Navigate to the test project folder
    npm install  # Ensure dependencies for WebdriverIO are installed
    npx wdio run wdio.conf.js  # Run WebdriverIO tests
  displayName: 'Run WebdriverIO Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: './webdriverio_test_project/junit-results/*.xml'
    failTaskOnFailedTests: true
