trigger:
  branches:
    include:
      - tests_enhacements  #branch

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x' 
  displayName: 'Install Node.js'

# Step to install Chrome browser
- script: |
    powershell -Command "Start-Process 'powershell' -ArgumentList '-NoProfile -ExecutionPolicy Bypass -Command Install-Module GoogleChrome; Install-GoogleChrome -Channel stable' -Verb runAs"
  displayName: 'Install Chrome Browser'

# Step to verify Chrome installation
- script: |
    google-chrome --version
  displayName: 'Verify Chrome Installation'

# Step to install frontend dependencies and build the frontend
- script: |
    npm install
    npm run build  
  displayName: 'Build Frontend'

# Step to install backend dependencies and run the backend
- script: |
    cd ./app-management 
    npm install
    npm start  
  displayName: 'Start Backend'

# Step to run WebdriverIO tests with debug logs
- script: |
    cd ./webdriverio_test_project
    npm install  
    npx wdio run wdio.conf.js --logLevel debug
  displayName: 'Run WebdriverIO Tests'


# Step to list contents of junit-results directory
- script: |
    cd ./webdriverio_test_project/junit-results
    ls
  displayName: 'Verify Test Results Directory'


- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'webdriverio_test_project/junit-results/*.xml'
    failTaskOnFailedTests: true
