const products = [
  // Telefony komórkowe - Smartfony
  {
    id: "1",
    name: "Smartfon Apple iPhone 14",
    category: "Telefony komórkowe",
    subcategory: "Smartfony",
    brand: "Apple",
    price: 3999,
    inStock: "Nie",
    promoted: false,
    os: "iOS 17",
    screenSize: '6.1"',
    storage: "128 GB",
    ram: "6 GB",
    battery: "4000 mAh",
    material: "",
    color: ["czarny"],
    chargerType: "",
    applicableModel: "",
    type: "",
    img: "/images/products/iphone14.jpg",
    status: 'active'
  },
  // Telefony komórkowe - Feature Phones
  {
    id: "2",
    name: "Nokia 3310",
    category: "Telefony komórkowe",
    subcategory: "Feature Phones",
    brand: "Nokia",
    price: 299,
    inStock: "Nie",
    promoted: false,
    os: "Nokia Series 30+",
    screenSize: '5.5"',
    storage: "32 GB",
    ram: "2 GB",
    battery: "3000 mAh",
    material: "",
    color: ["niebieski"],
    chargerType: "",
    applicableModel: "",
    type: "",
    img: "/images/products/nokia3310.jpg",
    status: 'active'
  },
  // Akcesoria - Etui
  {
    id: "3",
    name: "Etui silikonowe do iPhone 10",
    category: "Akcesoria",
    subcategory: "Etui",
    brand: "Apple",
    price: 99,
    inStock: "Tak",
    promoted: true,
    os: "",
    screenSize: "",
    storage: "",
    ram: "",
    battery: "",
    material: "silikon",
    color: ["czarny"],
    chargerType: "",
    applicableModel: "Iphone 10",
    type: "",
    img: "/images/products/etui_iphone10.jpg",
    status: 'active'
  },
  // Akcesoria - Szkła ochronne
  {
    id: "4",
    name: "Szkło ochronne do Samsung A70",
    category: "Akcesoria",
    subcategory: "Szkła ochronne",
    brand: "FOREVER",
    price: 69,
    inStock: "Tak",
    promoted: false,
    os: "",
    screenSize: '6.5"',
    storage: "",
    ram: "",
    battery: "",
    material: "",
    color: [],
    chargerType: "",
    applicableModel: "Galaxy A70",
    type: "",
    img: "/images/products/szklo_samsung_a70.jpg",
    status: 'active'
  },
  // Akcesoria - Ładowarki
  {
    id: "5",
    name: "Ładowarka Samsung Fast Charge",
    category: "Akcesoria",
    subcategory: "Ładowarki",
    brand: "Samsung",
    price: 79,
    inStock: "Tak",
    promoted: true,
    os: "",
    screenSize: "",
    storage: "",
    ram: "",
    battery: "",
    material: "",
    color: [],
    chargerType: "USB-C",
    applicableModel: "Galaxy S10",
    type: "",
    img: "/images/products/ladowarka_samsung.jpg",
    status: 'active'
  },
  // Akcesoria - Słuchawki
  {
    id: "6",
    name: "Słuchawki Apple AirPods",
    category: "Akcesoria",
    subcategory: "Słuchawki",
    brand: "Apple",
    price: 899,
    inStock: "Tak",
    promoted: false,
    os: "",
    screenSize: "",
    storage: "",
    ram: "",
    battery: "",
    material: "",
    color: ["biały"],
    chargerType: "",
    applicableModel: "Iphone 11",
    type: "douszne",
    img: "/images/products/airpods.jpg",
    status: 'active'
  },
  // Akcesoria - Powerbanki
  {
    id: "7",
    name: "Powerbank Xiaomi 5000mAh",
    category: "Akcesoria",
    subcategory: "Powerbanki",
    brand: "FOREVER",
    price: 129,
    inStock: "Tak",
    promoted: false,
    os: "",
    screenSize: "",
    storage: "",
    ram: "",
    battery: "5000 mAh",
    material: "",
    color: [""],
    chargerType: "",
    applicableModel: "Galaxy A40",
    type: "",
    img: "/images/products/powerbank_xiaomi.jpg",
    status: 'active'
  },
  // Additional Products for coverage
  {
    id: "8",
    name: "Samsung S10",
    category: "Telefony komórkowe",
    subcategory: "Smartfony",
    brand: "Samsung",
    price: 2999,
    inStock: "Tak",
    promoted: true,
    os: "Android 15",
    screenSize: '6.5"',
    storage: "128 GB",
    ram: "8 GB",
    battery: "4000 mAh",
    material: "",
    color: ["czarny"],
    chargerType: "",
    applicableModel: "",
    type: "",
    img: "/images/products/samsung_s21.jpg",
    status: 'active'
  },
  {
    id: "9",
    name: "Xiaomi Redmi Note 10",
    category: "Telefony komórkowe",
    subcategory: "Smartfony",
    brand: "Xiaomi",
    price: 1199,
    inStock: "Tak",
    promoted: false,
    os: "Android 13",
    screenSize: '6.1"',
    storage: "256 GB",
    ram: "6 GB",
    battery: "5000 mAh",
    material: "",
    color: ["niebieski"],
    chargerType: "",
    applicableModel: "",
    type: "",
    img: "/images/products/redmi_note_10.jpg",
    status: 'active'
  },
  {
    id: "10",
    name: "Apple iPhone SE (2022)",
    category: "Telefony komórkowe",
    subcategory: "Smartfony",
    brand: "Apple",
    price: 1999,
    inStock: "Nie",
    promoted: false,
    os: "iOS 18",
    screenSize: '5.5"',
    storage: "64 GB",
    ram: "2 GB",
    battery: "3000 mAh",
    material: "",
    color: ["biały"],
    chargerType: "",
    applicableModel: "",
    type: "",
    img: "/images/products/iphone_se_2022.jpg",
    status: 'active'
  },
];


export default products;
