const users = [
  { id: "1", userName: 'John Snow',address: 'Winterfell', avatar: '/images/users/Jon_Snow.jpg', email: 'john.snow@gmail.com', status: 'aktywny', title: 'Software Tester', fullName: 'John Snow Aegon Targaryen', dob: '1990-01-01', widgetLgDate: '2.08.2024', widgetLgAmount: '11130.00 PLN', widgetLgStatus: 'Zatwierdzona', joinDate: '10.08.2022',phone: '+48511511511', currentMainProject: 'Braavos web app'},
  { id: "2", userName: 'Arya Stark',address: 'Winterfell', avatar: '/images/users/Arya_Stark.png', email: 'arya.stark@gmail.com', status: 'zawieszony', title: 'Frontend Developer', fullName: 'Arya Stark', dob: '1995-05-01', widgetLgDate: '3.08.2024', widgetLgAmount: '17000.00 PLN', widgetLgStatus: 'W trakcie',joinDate: '12.04.2021',phone: '+48611611611', currentMainProject: ''},
  { id: "3", userName: 'Melisandre',address: 'City of Asshai', avatar: '/images/users/Melisandre.jpg', email: 'melisandre@gmail.com', status: 'nieaktywny', title: 'Backend Developer', fullName: 'Melisandre', dob: '1985-09-01', widgetLgDate: '1.08.2024', widgetLgAmount: '9000.00 PLN', widgetLgStatus: 'Odrzucona', joinDate: '10.08.2024',phone: '+48711611711', currentMainProject: 'Valyria web app'},
  { id: "4", userName: 'Cersei Lanister',address: 'Casterly Rock', avatar: '/images/users/Cersei_Lannister.png', email: 'cersei.lanister@gmail.com', status: 'aktywny', title: 'Frontend Developer', fullName: 'Cersei Lanister', dob: '1980-11-01', widgetLgDate: '4.08.2024', widgetLgAmount: '18000.00 PLN', widgetLgStatus: 'Zatwierdzona' , joinDate: '11.04.2022',phone: '+78711811311', currentMainProject: 'Valyria web app'},
  { id: "5", userName: 'Daenerys Targaryen',address: 'Dragonstone', avatar: '/images/users/Denerys_Targaryen.jpg', email: 'daenerys.targaryen@gmail.com', status: 'aktywny', title: 'Business Analyst', fullName: 'Daenerys Targaryen Stormborn Khaleesi', dob: '1992-02-01', widgetLgDate: '5.08.2024', widgetLgAmount: '11200.00 PLN', widgetLgStatus: 'W trakcie', joinDate: '1.03.2012',phone: '+32121281131', currentMainProject: 'Glitch web app'},
  { id: "6", userName: 'Joffrey Baratheon',address: 'Kings Landing, Westeros', avatar: '/images/users/Joffrey_Baratheon.jpg', email: 'joffrey.baratheon@gmail.com', status: 'aktywny', title: 'Frontend Developer', fullName:'Joffrey Baratheon 1st of this name', dob: '1994-04-01', widgetLgDate: '6.08.2024', widgetLgAmount: '12000.00 PLN', widgetLgStatus: 'Odrzucona', joinDate: '11.08.2013',phone: '+7823811311', currentMainProject: 'Cytadela mobile app'},
  { id: "7", userName: 'Jamie Lannister',address: 'Casterly Rock', avatar: '/images/users/Jamie_Lannister.png', email: 'jamie.lanister@gmail.com', status: 'zawieszony', title: 'Chapter Lead', fullName:  'Jamie Lannister Kingslayer', dob: '1988-07-01', widgetLgDate: '7.08.2024', widgetLgAmount: '13000.00 PLN', widgetLgStatus: 'Zatwierdzona', joinDate: '1.08.2024',phone: '', currentMainProject: 'Winterfell mobile app'},
  { id: "8", userName: 'Margery Tyrell',address: 'Highgarden', avatar: '/images/users/Margery_Tyrell.png', email: 'margery.tyrell@gmail.com', status: 'aktywny', title: 'Frontend Developer', fullName: 'Margery Tyrell', dob: '1996-09-01', widgetLgDate: '8.08.2024', widgetLgAmount: '17000.00 PLN', widgetLgStatus: 'W trakcie', joinDate: '13.11.2021',phone: '+87331321311', currentMainProject: 'Winterfell web app'},
  { id: "9", userName: 'Petyr Baelish',address: 'Riverrun castle', avatar: '/images/users/Petyr_Bealish.jpg', email: 'petyr.baelish@gmail.com', status: 'aktywny', title: 'Backend Developer', fullName: 'Petyr Baelish', dob: '1960-12-01', widgetLgDate: '9.08.2024', widgetLgAmount: '8700.00 PLN', widgetLgStatus: 'Odrzucona', joinDate: '12.08.2024',phone: '+37711221211', currentMainProject: 'Winterfell web app'},
  { id: "10", userName: 'Robert Baratheon',address: 'Storms End', avatar: '/images/users/Robert_Baratheon.jpg', email: 'robert.baratheon@gmail.com', status: 'aktywny', title: 'Backend Developer', fullName: 'Robert Baratheon', dob: '1956-03-01', widgetLgDate: '10.08.2024', widgetLgAmount: '10000.00 PLN', widgetLgStatus: 'Zatwierdzona', joinDate: '5.07.2024',phone: '+58711811311', currentMainProject: 'Braavos web app'},
];

export default users;

